[package]
name = "avila-quinn"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
name = "avila_quinn"
path = "src/lib.rs"

[dependencies]
avila-nucleus = { path = "../avila-nucleus" }
avila-primitives = { path = "../avila-primitives" }
avila-crypto = { path = "../avila-crypto" }

[features]
default = []
