[package]
name = "avila-primitives"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "avila_primitives"
path = "src/lib.rs"

[dependencies]
avila-nucleus = { path = "../avila-nucleus" }

[dev-dependencies]
criterion = "0.5"
hex = "0.4"

# [[bench]]
# name = "bigint_ops"
# harness = false
