[package]
name = "avila-math"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
name = "avila_math"
path = "src/lib.rs"

[dependencies]
avila-nucleus = { path = "../avila-nucleus" }
avila-primitives = { path = "../avila-primitives" }

[features]
default = []
