[package]
name = "avila-regex"
version = "0.1.0"
edition = "2021"
authors = ["Nícolas Ávila <nicolas@avila.inc>"]
license = "MIT OR Apache-2.0"
description = "Regex nativo - substitui regex"

[lib]
name = "avila_regex"
path = "src/lib.rs"
